kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ecp-chart.fullname" . }}-file-assets-pvc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ecp-chart.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.global.storage.storageClassName }}
  accessModes:
    - {{ .Values.global.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.ecp.storage.fileAsserts }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emqx-ecp-promtheus-data-pvc
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.global.storage.storageClassName }}
  accessModes:
    - {{ .Values.global.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.prometheusData }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ecp-chart.fullname" . }}-promtheus-config-pvc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ecp-chart.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.global.storage.storageClassName }}
  accessModes:
    - {{ .Values.global.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.prometheusConfig }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ecp-chart.fullname" . }}-alertmanager-data-pvc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ecp-chart.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.global.storage.storageClassName }}
  accessModes:
    - {{ .Values.global.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.alertmanagerData }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ecp-chart.fullname" . }}-alertmanager-config-pvc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ecp-chart.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.global.storage.storageClassName }}
  accessModes:
    - {{ .Values.global.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.alertmanagerConfig }}
