kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emqx-ecp-file-assets-pvc
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.ecpFileAsserts }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emqx-ecp-promtheus-data-pvc
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.ecpPrometheusData }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emqx-ecp-promtheus-config-pvc
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.ecpPrometheusConfig }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emqx-ecp-alertmanager-data-pvc
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.ecpAlertmanagerData }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emqx-ecp-alertmanager-config-pvc
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.ecpAlertmanagerConfig }}
