apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecp-chart.fullname" . }}-docker-registry
  labels:
    {{- include "ecp-chart.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
